
module.exports = {
	USER_INFO: 'USER_INFO',
	TOKEN: 'TOKEN',
	BACK_URL: 'BACK_URL',
	CONFIG: 'CONFIG',
	INVITE_CODE: 'INVITE_CODE',
	TEMP_TOKEN: 'TEMP_TOKEN',
	/* 保存最近的筛选为默认筛选 */
	DEFAULT_FILTER:'DEFAULT_FILTER',
}